routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\FeedController;
use App\Http\Controllers\MeetupController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PatronController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SitemapController;
use App\Http\Controllers\SocialController;
use App\Http\Controllers\StatusController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\TelegramController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WebhookController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Auth::routes();
Auth::routes(['verify' => true]);

// Social Auth
Route::get('login/{provider}', [SocialController::class, 'redirect']);
Route::get('login/{provider}/callback', [SocialController::class, 'Callback']);

// 404 Fallback
Route::fallback(function () {
    return response()->view('errors.404', [], 404);
});

// Routes with throttle
Route::group(['middleware' => ['throttle:60,1']], function () {
    // Home
    Route::view('/', 'home.home')->name('home');

    // Explore
    Route::view('/explore', 'explore.explore')->name('explore')->middleware('staff');

    // User
    Route::group(['prefix' => '@{username}', 'as' => 'user.'], function () {
        Route::get('', [UserController::class, 'profile'])->name('done');
        Route::get('pending', [UserController::class, 'profile'])->name('pending');
        Route::get('products', [UserController::class, 'profile'])->name('products');
        Route::get('questions', [UserController::class, 'profile'])->name('questions');
        Route::get('answers', [UserController::class, 'profile'])->name('answers');
        Route::get('following', [UserController::class, 'profile'])->name('following');
        Route::get('followers', [UserController::class, 'profile'])->name('followers');
        Route::get('stats', [UserController::class, 'profile'])->name('stats');
    });

    // Settings
    Route::group(['prefix' => 'settings', 'as' => 'user.settings.', 'middleware' => ['auth']], function () {
        Route::get('', [UserController::class, 'profileSettings'])->name('profile');
        Route::get('account', [UserController::class, 'accountSettings'])->name('account');
        Route::get('patron', [UserController::class, 'patronSettings'])->name('patron');
        Route::get('password', [UserController::class, 'passwordSettings'])->name('password');
        Route::get('notifications', [UserController::class, 'notificationsSettings'])->name('notifications');
        Route::get('integrations', [UserController::class, 'integrationsSettings'])->name('integrations');
        Route::get('api', [UserController::class, 'apiSettings'])->name('api');
        Route::get('logs', [UserController::class, 'logsSettings'])->name('logs');
        Route::get('data', [UserController::class, 'dataSettings'])->name('data');
        Route::get('delete', [UserController::class, 'deleteSettings'])->name('delete');
        Route::get('export/account', [UserController::class, 'exportAccount'])->name('export.account');
        Route::get('export/logs', [UserController::class, 'exportLogs'])->name('export.logs');
    });

    // Notifications
    Route::group(['prefix' => 'notifications', 'as' => 'notifications.', 'middleware' => ['auth']], function () {
        Route::view('', 'notifications.unread')->name('unread');
        Route::view('all', 'notifications.all')->name('all');
    });

    // Suspended
    Route::view('suspended', 'auth.suspended')->name('suspended');

    // Avatar
    Route::get('avatar/{username}.png', [UserController::class, 'avatar'])->name('avatar');

    // Webhooks
    Route::group(['prefix' => 'webhook'], function () {
        Route::post('web/{token}', [WebhookController::class, 'web']);
        Route::post('version/{appkey}', [WebhookController::class, 'newVersion']);
    });

    // Product
    Route::group(['prefix' => 'product/{slug}', 'as' => 'product.'], function () {
        Route::get('', [ProductController::class, 'profile'])->name('done');
        Route::get('pending', [ProductController::class, 'profile'])->name('pending');
        Route::get('updates', [ProductController::class, 'profile'])->name('updates');
        Route::get('subscribers', [ProductController::class, 'profile'])->name('subscribers');
    });

    // Products
    Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
        Route::get('', [ProductController::class, 'newest'])->name('newest');
        Route::get('launched', [ProductController::class, 'launched'])->name('launched');
    });

    // Question
    Route::group(['prefix' => 'question', 'as' => 'question.'], function () {
        Route::get('{id}', [QuestionController::class, 'question'])->name('question');
    });

    // Questions
    Route::group(['prefix' => 'questions', 'as' => 'questions.'], function () {
        Route::get('', [QuestionController::class, 'newest'])->name('newest');
        Route::get('unanswered', [QuestionController::class, 'unanswered'])->name('unanswered');
        Route::get('popular', [QuestionController::class, 'popular'])->name('popular');
    });

    // Search
    Route::group(['prefix' => 'search', 'as' => 'search.'], function () {
        Route::get('', [SearchController::class, 'search'])->name('home');
        Route::get('tasks', [SearchController::class, 'tasks'])->name('tasks');
        Route::get('comments', [SearchController::class, 'comments'])->name('comments');
        Route::get('questions', [SearchController::class, 'questions'])->name('questions');
        Route::get('answers', [SearchController::class, 'answers'])->name('answers');
        Route::get('products', [SearchController::class, 'products'])->name('products');
        Route::get('users', [SearchController::class, 'users'])->name('users');
    });

    // Admin
    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['staff']], function () {
        Route::view('users', 'admin.users')->middleware('password.confirm')->name('users');
        Route::view('tasks', 'admin.tasks')->middleware('password.confirm')->name('tasks');
        Route::view('activities', 'admin.activities')->middleware('password.confirm')->name('activities');
        Route::get('adminbar', [AdminController::class, 'toggle'])->name('adminbar');
    });

    // Patron
    Route::group(['prefix' => 'patron', 'as' => 'patron.'], function () {
        Route::view('', 'pages.patron')->name('home');
    });

    // Paddle Integration
    Route::post('paddle/webhook', [PatronController::class, 'handleWebhook'])->name('paddle.webhook');

    // Dark mode
    Route::get('darkmode', [UserController::class, 'darkMode'])->name('darkmode')->middleware('patron');

    // Single Task and comment
    Route::group(['prefix' => 'task'], function () {
        Route::get('{id}', [TaskController::class, 'task'])->name('task');
        Route::get('{id}/{comment_id}', [TaskController::class, 'comment'])->name('comment');
    });

    // Zen mode tasks
    Route::view('tasks', 'tasks.tasks')->name('tasks')->middleware('auth');

    // Pages
    Route::view('about', 'pages.about')->name('about');
    Route::view('terms', 'pages.terms')->name('terms');
    Route::view('privacy', 'pages.privacy')->name('privacy');
    Route::view('security', 'pages.security')->name('security');
    Route::view('sponsors', 'pages.sponsors')->name('sponsors');
    Route::view('contact', 'pages.contact')->name('contact');
    Route::view('reputation', 'pages.reputation')->name('reputation')->middleware('auth');
    Route::view('open', 'pages.open')->name('open');
    Route::get('deals', [PagesController::class, 'deals'])->name('deals');

    // Meetups
    Route::group(['prefix' => 'meetups', 'as' => 'meetups.'], function () {
        Route::get('/', [MeetupController::class, 'meetups'])->name('home')->middleware('staff');
        Route::get('/rsvpd', [MeetupController::class, 'rsvpd'])->name('rsvpd')->middleware('staff');
        Route::get('/finished', [MeetupController::class, 'finished'])->name('finished')->middleware('staff');
    });

    // https://web.dev/change-password-url
    Route::get('.well-known/change-password', function () {
        return redirect()->route('user.settings.password');
    });

    // Sitemaps
    Route::get('sitemap_users.txt', [SitemapController::class, 'users']);
    Route::get('sitemap_products.txt', [SitemapController::class, 'products']);
    Route::get('sitemap_questions.txt', [SitemapController::class, 'questions']);
    Route::get('sitemap_tasks.txt', [SitemapController::class, 'tasks']);
    Route::get('sitemap_comments.txt', [SitemapController::class, 'comments']);
    Route::view('sitemap_urls.txt', 'seo.sitemap_urls');

    // Status
    Route::group(['prefix' => 'status'], function () {
        Route::get('ping', [StatusController::class, 'ping']);
        Route::get('redis', [StatusController::class, 'redis']);
        Route::get('memcached', [StatusController::class, 'memcached']);
    });

    // Feed
    Route::group(['prefix' => 'feed', 'as' => 'feed.'], function () {
        Route::get('user/{username}/{page?}', [FeedController::class, 'user'])->name('user');
        Route::get('product/{slug}/{page?}', [FeedController::class, 'product'])->name('product');
    });
});

// Mention
Route::group(['prefix' => 'mention', 'middleware' => ['auth']], function () {
    Route::get('users', [UserController::class, 'mention']);

app/Http/Livewire/Admin/Activities.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use Livewire\WithPagination;
use Spatie\Activitylog\Models\Activity;

class Activities extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public $readyToLoad = false;

    public function loadActivities()
    {
        $this->readyToLoad = true;
    }

    public function render()
    {
        $activities = Activity::latest()->paginate('50');
        $count = Activity::all()->count('id');

        return view('livewire.admin.activities', [
            'activities' => $this->readyToLoad ? $activities : [],
            'count' => number_format($count),
        ]);
    }
}

app/Http/Livewire/Admin/Adminbar.php
<?php

namespace App\Http\Livewire\Admin;

use App\Jobs\Clean;
use App\Models\Answer;
use App\Models\Comment;
use App\Models\Product;
use App\Models\Question;
use App\Models\Task;
use App\Models\User;
use App\Models\Webhook;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Queue;
use Livewire\Component;
use Spatie\Activitylog\Models\Activity;

class Adminbar extends Component
{
    protected $listeners = [
        'refreshStats' => 'render',
    ];

    public function refreshStats()
    {
        loggy(request()->ip(), 'Admin', auth()->user(), 'Refreshed Adminbar Status');

        $this->emitSelf('refreshStats');
    }

    public function clean()
    {
        Clean::dispatch()->delay(now()->addSeconds(10));
        loggy(request()->ip(), 'Admin', auth()->user(), 'Cleaned the Application');

        return $this->alert('success', 'Cleaning process has been initiated successfully 🧼');
    }

    public function render()
    {
        $branch = git('rev-parse --abbrev-ref HEAD') ?: 'main';
        $commit = git('rev-parse --short HEAD') ?: '0000000';

        // DB Details
        $tasks = Task::count('id');
        $users = User::count('id');
        $products = Product::count('id');
        $reputations = User::sum('reputation');
        $questions = Question::count('id');
        $answers = Answer::count('id');
        $comments = Comment::count('id');
        $webhooks = Webhook::count('id');
        $notifications = DB::table('notifications')->count('id');
        $logs = Activity::count('id');
        $interactions = DB::table('interactions')->count();
        $praises = DB::table('interactions')->whereRelation('like')->count();
        $jobs = Queue::size();

        return view('livewire.admin.adminbar', [
            'branchname' => $branch,
            'headHASH' => $commit,
            'tasks' => number_format($tasks),
            'users' => number_format($users),
            'products' => number_format($products),
            'reputations' => number_format($reputations),
            'questions' => number_format($questions),
            'answers' => number_format($answers),
            'comments' => number_format($comments),
            'notifications' => number_format($notifications),
            'interactions' => number_format($interactions),
            'logs' => number_format($logs),
            'praises' => number_format($praises),
            'jobs' => number_format($jobs),
            'webhooks' => number_format($webhooks),
        ]);
    }
}

app/Http/Livewire/Admin/Tasks.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Task;
use Livewire\Component;
use Livewire\WithPagination;

class Tasks extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public $readyToLoad = false;

    public function loadTasks()
    {
        $this->readyToLoad = true;
    }

    public function render()
    {
        $tasks = Task::latest()->paginate(50);
        $count = Task::all()->count('id');

        return view('livewire.admin.tasks', [
            'tasks' => $this->readyToLoad ? $tasks : [],
            'count' => $this->readyToLoad ? $count : [],
        ]);
    }
}

app/Http/Livewire/Admin/Users.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;

class Users extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public $readyToLoad = false;

    public function loadUsers()
    {
        $this->readyToLoad = true;
    }

    public function render()
    {
        $users = User::latest('last_active')->paginate(50);
        $count = User::all()->count('id');

        return view('livewire.admin.users', [
            'users' => $this->readyToLoad ? $users : [],
            'count' => $this->readyToLoad ? $count : [],
        ]);
    }
}

app/Http/Livewire/Answer/Answers.php
<?php

namespace App\Http\Livewire\Answer;

use App\Models\Answer;
use App\Models\Question;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Livewire\Component;

class Answers extends Component
{
    public $listeners = [
        'answerAdded' => 'render',
        'answerDeleted' => 'render',
    ];

    public Question $question;
    public $page;
    public $perPage;
    public $readyToLoad = false;

    public function mount($question, $page, $perPage)
    {
        $this->question = $question;
        $this->page = $page ? $page : 1;
        $this->perPage = $perPage ? $perPage : 1;
    }

    public function loadAnswers()
    {
        $this->readyToLoad = true;
    }

    public function paginate($items, $options = [])
    {
        $page = $this->page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);

        return new LengthAwarePaginator($items->forPage($page, $this->perPage), $items->count(), $this->perPage, $page, $options);
    }

    public function render()
    {
        $answers = Answer::cacheFor(60 * 60)
            ->where('question_id', $this->question->id)
            ->whereHas('user', function ($q) {
                $q->where([
                    ['isFlagged', false],
                ]);
            })
            ->orderBy('created_at', 'DESC')
            ->get();

        return view('livewire.answer.answers', [
            'answers' => $this->readyToLoad ? $this->paginate($answers) : [],
            'page' => $this->page,
        ]);
    }
}

app/Http/Livewire/Comment/Comments.php
<?php

namespace App\Http\Livewire\Comment;

use App\Models\Comment;
use App\Models\Task;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Livewire\Component;

class Comments extends Component
{
    public $listeners = [
        'commentAdded' => 'render',
        'commentDeleted' => 'render',
    ];

    public Task $task;
    public $page;
    public $perPage;
    public $readyToLoad = false;

    public function mount($task, $page, $perPage)
    {
        $this->task = $task;
        $this->page = $page ? $page : 1;
        $this->perPage = $perPage ? $perPage : 1;
    }

    public function loadComments()
    {
        $this->readyToLoad = true;
    }

    public function paginate($items, $options = [])
    {
        $page = $this->page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);

        return new LengthAwarePaginator($items->forPage($page, $this->perPage), $items->count(), $this->perPage, $page, $options);
    }

    public function render()
    {
        $comments = Comment::cacheFor(60 * 60)
            ->where('task_id', $this->task->id)
            ->whereHas('user', function ($q) {
                $q->where([
                    ['isFlagged', false],
                ]);
            })
            ->oldest()
            ->get();

        return view('livewire.comment.comments', [
            'comments' => $this->readyToLoad ? $this->paginate($comments) : [],
            'page' => $this->page,
        ]);
    }
}

resources/views/livewire/admin/tasks.blade.php
<div class="card" wire:init="loadTasks">
    <div class="card-header h6 pt-3 pb-3">
        <div class="h5">Tasks</div>
        <span class="fw-bold">{{ $readyToLoad ? $count : '···' }}</span>
        total tasks
    </div>
    <div class="table-responsive">
        @if ($readyToLoad)
        <table class="table text-dark">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Username</th>
                    <th scope="col">Status</th>
                    <th scope="col">Task</th>
                    <th scope="col">Updated</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($tasks as $task)
                <tr>
                    <th>{{ $task->id }}</th>
                    <td>
                        <a href="{{ route('user.done', ['username' => $task->user->username]) }}" target="_blank">
                            {{ '@'.$task->user->username }}
                        </a>
                    </td>
                    <td>
                        @if ($task->done)
                        ✅
                        @else
                        ⌛
                        @endif
                    </td>
                    <td>
                        <a href="{{ route('task', ['id' => $task->id]) }}">
                            {{ Str::limit($task->task, '100') }}
                        </a>
                        @if ($task->hidden)
                        <span title="Flagged">🤢</span>
                        @endif
                    </td>
                    <td>
                        <span title="{{ $task->updated_at->format('M d, Y g:i A') }}">
                            {{ $task->updated_at->format('M d, Y') }}
                        </span>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @endif
        @if (!$readyToLoad)
        <div class="card-body text-center mt-3">
            <div class="spinner-border taskord-spinner text-secondary mb-3" role="status"></div>
            <div class="h6">
                Loading Tasks...
            </div>
        </div>
        @endif
    </div>
    {{ $readyToLoad ? $tasks->links() : '' }}
</div>

resources/views/livewire/admin/users.blade.php
<div class="card" wire:init="loadUsers">
    <div class="card-header h6 pt-3 pb-3">
        <div class="h5">Users</div>
        <span class="fw-bold">{{ $readyToLoad ? $count : '···' }}</span>
        total users
    </div>
    <div class="table-responsive">
        @if ($readyToLoad)
        <table class="table text-dark">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Avatar</th>
                    <th scope="col">Name</th>
                    <th scope="col">Username</th>
                    <th scope="col">Email</th>
                    <th scope="col">Patron</th>
                    <th scope="col">Last IP</th>
                    <th scope="col">Via</th>
                    <th scope="col">Last active</th>
                    <th scope="col">More</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($users as $user)
                <tr>
                    <th>{{ $user->id }}</th>
                    <td>
                        <img loading=lazy class="avatar-30 rounded-circle me-2" src="{{ Helper::getCDNImage($user->avatar, 80) }}" height="30" width="30" alt="{{ $user->username }}'s avatar" />
                    </td>
                    <td class="fw-bold">
                        @if (!$user->firstname and !$user->lastname)
                        <span class="small fw-bold text-secondary">Not Set</span>
                        @else
                        {{ $user->firstname.' '.$user->lastname }}
                        @endif
                        @if ($user->isVerified)
                            <x-heroicon-s-badge-check class="heroicon text-primary ms-1 verified" />
                        @endif
                    </td>
                    <td>
                        <a href="{{ route('user.done', ['username' => $user->username]) }}" target="_blank">
                            {{ '@'.$user->username }}
                        </a>
                        @if ($user->isSuspended)
                        <span title="Suspended">
                            🤢
                        </span>
                        @endif
                        @if ($user->isFlagged)
                        <span title="Flagged">
                            🚩
                        </span>
                        @endif
                    </td>
                    <td>
                        {{ $user->email }}
                        @if ($user->hasVerifiedEmail())
                        <span title="Email Verified">
                            <x-heroicon-o-check class="heroicon ms-1 text-success" />
                        </span>
                        @else
                        <span title="Email not Verified">
                            <x-heroicon-o-x class="heroicon ms-1 text-danger" />
                        </span>
                        @endif
                    </td>
                    <td>
                        @if (!$user->isPatron)
                        <span>
                            ❌
                        </span>
                        @else
                        <span>
                            💰
                            @if ($user->patron)
                            ⭐
                            @else
                            🎁
                            @endif
                        </span>
                        @endif
                    </td>
                    <td>
                        @if ($user->lastIP)
                        <a class="font-monospace" href="https://ipinfo.io/{{ $user->lastIP }}" title="{{ $user->lastIP }}" target="_blank" rel="noreferrer">
                            {{ Str::limit($user->lastIP, 15, '..') }}
                        </a>
                        @else
                        <span class="small fw-bold text-secondary">Not logged</span>
                        @endif
                    </td>
                    <td>
                        @if ($user->provider === 'google')
                            <img class="brand-icon" src="{{ asset('images/brand/google.svg') }}" />
                        @elseif ($user->provider === 'twitter')
                            <img class="brand-icon" src="{{ asset('images/brand/twitter.svg') }}" />
                        @elseif ($user->provider === 'github')
                            <img class="brand-icon github-logo" src="{{ asset('images/brand/github.svg') }}" />
                        @elseif ($user->provider === 'gitlab')
                            <img class="brand-icon" src="{{ asset('images/brand/gitlab.svg') }}" />
                        @else
                            <x-heroicon-o-globe-alt class="heroicon text-success" />
                        @endif
                    </td>
                    <td title="{{ carbon($user->last_active)->format('M d, Y g:i A') }}">
                        @if ($user->last_active)
                        @if (strtotime(carbon()) - strtotime($user->last_active) <= 5)
                        <span class="fw-bold text-success">active</span>
                        @else
                        {{ carbon($user->last_active)->diffForHumans() }}
                        @endif
                        @else
                        <span class="small fw-bold text-secondary">Not Set</span>
                        @endif
                    </td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-sm btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">
                                More
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <span class="dropdown-item">
                                        <x-heroicon-o-check class="heroicon text-secondary" />
                                        <span class="fw-bold">{{ $user->tasks()->count('id') }}</span> Tasks
                                    </span>
                                </li>
                                <li>
                                    <span class="dropdown-item">
                                        <x-heroicon-o-chat-alt class="heroicon text-secondary" />
                                        <span class="fw-bold">{{ $user->comments()->count('id') }}</span> Comments
                                    </span>
                                </li>
                                <li>
                                    <span class="dropdown-item">
                                        <x-heroicon-o-question-mark-circle class="heroicon text-secondary" />
                                        <span class="fw-bold">{{ $user->questions()->count('id') }}</span> Questions
                                    </span>
                                </li>
                                <li>
                                    <span class="dropdown-item">
                                        <x-heroicon-o-chat-alt-2 class="heroicon text-secondary" />
                                        <span class="fw-bold">{{ $user->answers()->count('id') }}</span> Answers
                                    </span>
                                </li>
                                <li>
                                    <span class="dropdown-item">
                                        <x-heroicon-o-cube class="heroicon text-secondary" />
                                        <span class="fw-bold">{{ $user->ownedProducts('id')->count('id') }}</span> Products
                                    </span>
                                </li>
                                <li>
                                    <span class="dropdown-item">
                                        <x-heroicon-o-user-add class="heroicon text-secondary" />
                                        <span class="fw-bold">{{ $user->products()->count() }}</span> Membership
                                    </span>
                                </li>
                                <li>
                                    <span class="dropdown-item">
                                        <x-heroicon-o-bell class="heroicon text-secondary" />
                                        <span class="fw-bold">{{ $user->notifications()->count('id') }}</span> Notifications
                                    </span>
                                </li>
                                <li>
                                    <span class="dropdown-item">
                                        <x-heroicon-o-cloud-upload class="heroicon text-secondary" />
                                        <span class="fw-bold">{{ $user->webhooks()->count('id') }}</span> Webhooks
                                    </span>
                                </li>
                                <li>
                                    <span class="dropdown-item">
                                        <x-heroicon-o-clock class="heroicon text-secondary" />
                                        <span class="fw-bold">{{ $user->timezone }}</span>
                                    </span>
                                </li>
                                <li>
                                    <span class="dropdown-item" title="{{ $user->updated_at->format('M d, Y g:i A') }}">
                                        <x-heroicon-o-calendar class="heroicon text-secondary" />
                                        <span class="fw-bold">{{ $user->updated_at->format('M d, Y') }}</span>
                                    </span>
                                </li>
                                <li>
                                    <span class="dropdown-item" title="{{ $user->created_at->format('M d, Y g:i A') }}">
                                        <x-heroicon-o-calendar class="heroicon text-secondary" />
                                        <span class="fw-bold">{{ $user->created_at->format('M d, Y') }}</span>
                                        @if ($user->created_at->diffInDays(carbon('today')) < 7)
                                            🆕
                                        @endif
                                    </span>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @endif
        @if (!$readyToLoad)
        <div class="card-body text-center mt-3">
            <div class="spinner-border taskord-spinner text-secondary mb-3" role="status"></div>
            <div class="h6">
                Loading Users...
            </div>
        </div>
        @endif
    </div>
    {{ $readyToLoad ? $users->links() : '' }}
</div>